---
abstract: 'Hierarchical time logging'
author:
  - 'Sergei Svistunov <sergei-svistunov@yandex.ru>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: QBit-TimeLog
requires:
  QBit::Class: 0
  Time::HiRes: 0
  base: 0
  overload: 0
  qbit: 0
version: 0.3
